module.exports = [

    {id : "1" , title : "Curso de graphql 2" , views : 1000},
    {id : "2" , title : "Curso de JavaScripts" , views : 2000},
    {id : "3" , title : "Curso de x" , views : 2000},
    {id : "4" , title : "Curso de y" , views : 3000},
    {id : "5" , title : "Curso de z" , views : 7000},
    {id : "6" , title : "Curso de t" , views : 7000},
    {id : "7" , title : "Curso de o" , views : 9000},
    {id : "7" , title : "Curso de p" , views : 9000},
    {id : "7" , title : "Curso de q" , views : 9000},
    {id : "7" , title : "Curso de r" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},
    {id : "7" , title : "Curso de s" , views : 9000},


]   